spring.application.name=connexion-backend
server.port=8081

spring.datasource.url=jdbc:sqlserver://atesabd.database.windows.net:1433;database=serveratesa;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

spring.datasource.username=adminucr
spring.datasource.password=atesa123@
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
